services:
  - type: web
    name: diia-backend
    runtime: python
    plan: free
    pythonVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py render_server:flask_app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        value: "postgresql://postdia_user:kkRbzuUDLdnDvSUym3PvulCHtI815RQq@dpg-d3v8t5hr0fns73c9tq9g-a/postdia"
      - key: PORT
        fromService:
          type: web
          name: diia-backend
          property: port
      - key: ADMIN_IDS
        value: "448592121"
      - key: CRYPTOPAY_TOKEN
        value: "479115:AARxfBgUT3h1n9oBCwY1Y3UbgwN1n6S9mHn"
      - key: CLOUDINARY_CLOUD_NAME
        value: "djoszn8zc"
      - key: CLOUDINARY_API_KEY
        value: "472899494355635"
      - key: CLOUDINARY_API_SECRET
        value: "gGgIhXupY9im376HqlyCwNhZe-c"
    healthCheckPath: /api/health
    autoDeploy: true
